stages:
  data_validation:
    cmd: python validation.py
    deps:
      - validation.py
      - Training_Batch_Files
    outs:
      - data/Training_FileFromDB/InputFile.csv

  training_stage:
    cmd: python training.py
    deps:
      - training.py
      - data/Training_FileFromDB/InputFile.csv
    outs:
      - models/