stages:
  data_validation:
    cmd: python src/validation.py
    deps:
      - src/validation.py
      - Training_Batch_Files
    outs:
      - data/Training_FileFromDB/InputFile.csv

  training_stage:
    cmd: python src/training.py
    deps:
      - data/Training_FileFromDB/InputFile.csv
    outs:
      - models/